version: "1.0"

services:

  postgres:
    image: postgres:16.0-alpine
    container_name: postgres-tinyurl
    ports:
      - 55432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres



